### ISSUE TITLE
in OpenSSL 1.1.0 

### ISSUE THREAD

**Issue by xdeng** [paulej/AESKeyWrap#1]
in OpenSSL 1.1.0

EVP_CIPHER_CTX_new replace EVP_CIPHER_CTX_init

EVP_CIPHER_CTX_free replace  EVP_CIPHER_CTX_cleanup

thk

**Comment by paulej** [comment]
This has been sitting here for 2 years.  One of these days, I'll get around to fixing it.  I appreciate you pointing this out, and I should have said so long ago.

**Comment by paulej** [comment]
I finally got around to it, because I need to use this code to actually test against another implementation.  Weird what motivates a person, but it is now done.
